import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import DefaultNavBar from './components/Navbar'
import FlowbiteContext from './components/FlowbiteContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-900 h-screen flex flex-col">
        <DefaultNavBar />
        <FlowbiteContext>
        {children}
        </FlowbiteContext>
      </body>
    </html>
  )
}
